Repository CA-G12/5-ecommerce, pull requests merged in 2022-07, with the labels that each got.

#2 file struture
  cart.html
  dom.js
  form-add.html
  home-page.html
  logic.js
  test.js
  toggle.html
Labels: approve

#4 3 file structure re assign
  assets/style/cart.css
  assets/style/form-add.css
  assets/style/home-page.css
  assets/style/toggle.css
  js/dom.js
  js/logic.js
  js/test.js
Labels: Awaiting review

#9 Building home page
  assets/commerce-logo.png
  assets/e-commerce icon.webp
  home-page.html
  style.css
Labels: done

#11 8 form page
  assets/commerce-logo.png
  assets/e-commerce icon.webp
  assets/style/form-add.css
  assets/style/home-page.css
  form-add.html
  home-page.html
Labels: approve

#10 create landing page
  assets/style/Landing-page.css
  landing-page.html
Labels: approve

#14 Landing page
  assets/landing.png
  assets/style/Landing-page.css
  assets/style/home-page.css
  home-page.html
  index.html
Labels: done

#12 6 bulding styling home page
  assets/landing.png
  assets/style/Landing-page.css
  assets/style/home-page.css
  assets/style/index.css
  form-add.html
  home-page.html
  index.html
  toggle.html
Labels: done

#16 edit the style and page structure and add the script code
  assets/joel-filipe-jU9VAZDGMzs-unsplash.jpg
  assets/style/form-add.css
  form-add.html
  js/dom.js
Labels: approve

#17 7 cart page
  assets/style/cart.css
  cart.html
  home-page.html
Labels: Awaiting review

#21 add media query to make the page responsive
  assets/style/cart.css
Labels: Awaiting review

#30 Adding quantity and add to cart button
  home-page.html
  js/dom.js
  js/form.js
  js/home.js
Labels: done

#32 29 edit functionality
  README.md
  assets/style/home-page.css
  home-page.html
  js/dom.js
  js/form.js
  js/home.js
Labels: Awaiting review

#39 Fixing Bugs
  assets/style/cart.css
  assets/style/toggle.css
  cart.html
  home-page.html
  js/dom.js
  js/form.js
  js/home.js
  js/index.js
Labels: done
